apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: januaries.roger.alpha.example.com
  annotations:
    "api-approved.kubernetes.io": "unapproved, experimental-only; please get an approval from Kubernetes API reviewers if you're trying to develop a CRD in the *.k8s.io or *.kubernetes.io groups"
spec:
  group: roger.alpha.example.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 4
            status:
              type: object
              properties:
                availableReplicas:
                  type: integer

  names:
    kind: January
    singular: january
    plural: januaries
    shortNames:
      - jan
  scope: Namespaced