apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: januarys.roger.alpha.example.com
spec:
  group: roger.alpha.example.com
  versions:
    - name: v1alpha
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 4

  names:
    kind: January
    singular: january
    plural: januarys
    shortNames:
      - jan
  scope: Namespaced