apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp-dev-consumer
    component: consumer
    controller: web-crd-test
    pod-template-hash: 64c8875678
  name: webapp-crd-service-nodeport
  namespace: crd-test
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    controller: web-crd-test
  type: NodePort
